### ISSUE TITLE
Register new versions

### ISSUE THREAD

**Issue by Arkoniak** [tecosaur/DotEnv.jl#10]
One last comment, can we please register a new version, so it became accessible for all users?

1. First, write `@JuliaRegistrator register()` as a comment in this commit: https://github.com/vmari/DotEnv.jl/commit/5a1431d7447377c9cdbf70492e54754831b987c6 (it upgrade current version to 0.3.0)
2. Secondly write `@JuliaRegistrator register()` in this commit: https://github.com/vmari/DotEnv.jl/commit/2b6dbefce88749419ab847f225523039afe73db3 (but only after Registrator finished upgrading to 0.3.0).

**Comment by Arkoniak** [comment]
Ah, it looks like JuliaRegistrator is not installed in your repository. You can verify it in settings -> Integrations. If it is installed then you should see something like this:

![flameshot-2021-03-07T11-28-35](https://user-images.githubusercontent.com/2630519/110235370-540d8380-7f38-11eb-8a85-d46a4209a7cd.png)

In order to install JuliaRegistrator you need to follow instructions here https://github.com/JuliaRegistries/Registrator.jl

I think this part is relevant:

Go to https://juliahub.com and log in using your GitHub or GitLab account. Then click on "Register packages" on the left menu. There are also more detailed instructions [here](https://juliaregistries.github.io/Registrator.jl/stable/webui/#Usage-(For-Package-Maintainers)-1).

-- 

After installing JuliaRegistrator you need to issue `@JuliaRegistrator register` once more, to trigger the bot.

**Comment by vmari** [comment]
Fixed! Sorry for the delay. I've invited you as a contributor

**Comment by vmari** [comment]
https://github.com/JuliaRegistries/General/pull/32811 & https://github.com/JuliaRegistries/General/pull/32806
