### ISSUE TITLE
Support export at line start

### ISSUE THREAD

**Issue by onetonfoot** [tecosaur/DotEnv.jl#13]
Sometimes I have env files with the values

```
export KEY=VALUE
```

It would be great if this package also supported this, if you are open to it I'm happy to submit a pull request

**Comment by onetonfoot** [comment]
Totally forgot about this here you go #14

**Comment by tecosaur** [comment]
Implemented in the parser rewrite 9f994579508518e48e371213f40901539c952623 :slightly_smiling_face:
