### ISSUE TITLE
I'm interested in adopting this package

### ISSUE THREAD

**Issue by tecosaur** [tecosaur/DotEnv.jl#15]
Hi Valentín,

From the lack of response to #14, I'm guessing you find yourself short of time or interest to maintain this package?

I ask because I like the idea of it, but am interested in extending it to fully support the canonical dotenv format (https://github.com/bkeepers/dotenv), as well as the ability to load _and_ unload dotenv files.

If you're up for it, I'd be interested in adopting this package, to make those improvements I mentioned, and so there's an active maintainer. I've got half a dozen registered packages, including a similar "system utility" type one (https://github.com/tecosaur/BaseDirs.jl) and so am pretty confident in my ability to do so.

I hope this isn't too forward, but I'd be keen to hear what you think of this idea :slightly_smiling_face:
Timothy.

**Comment by tecosaur** [comment]
Oh, for reference, this is what such a change in ownership might look like: https://github.com/JuliaRegistries/General/pull/56157

**Comment by tecosaur** [comment]
Hi Valentín, it would be great to hear back from you :slightly_smiling_face:.

In the meantime, I will open a PR to general in case you aren't able to find the time to respond to this, so that this package can get some maintenance.

**Comment by nateybear** [comment]
@tecosaur I wrote the issue I opened this morning on the bus and looking back at it later, I see this issue from you! I would love to be in the loop on your becoming maintainer, and I can volunteer time to add features to DotEnv.jl

**Comment by DilumAluthge** [comment]
Bump @vmari

**Comment by DilumAluthge** [comment]
Cross-ref: https://github.com/JuliaRegistries/General/pull/98762

**Comment by tecosaur** [comment]
Resolved :slightly_smiling_face:. @vmari thanks for facilitating this, and for your work with the package up till now! :heart:
