### ISSUE TITLE
Add $ substitution

### ISSUE THREAD

**Issue by nateybear** [tecosaur/DotEnv.jl#16]
It would be nice for me to have $ substitution like bash in evaluating env variables. For example,

`DATA_PATH=$WORK/data`

I think expected behavior would be to evaluate WORK in the current environment and substitute it into the string. 

I’m happy to add a pull request and tests when I have time.

**Comment by tecosaur** [comment]
Implemented in dd185966d2047deea89de74f02af7acfbec93686 :slightly_smiling_face:
