### ISSUE TITLE
DotEnv.config() option to work in a silent mode

### ISSUE THREAD

**Issue by awojtas-r** [tecosaur/DotEnv.jl#17]
Hi,
while loading DotEnv.config() all AWS credentials are printed in the console. Is it possible to have a 'silent' function to load everything in the backgruond without printing? It would be useful during online sessions with students

Thanks!
Adam

**Comment by tecosaur** [comment]
Hi Adam,

How about just putting a semicolon at the end of the line? That suppresses the display of output in the REPL.

```julia
julia> 1 + 1
2

julia> 1 + 1;

julia> 
```

**Comment by awojtas-r** [comment]
That works as well, I've been thinking about built in function but your solution solves the issue, thank you!

**Comment by tecosaur** [comment]
Glad to hear, an extra function just seems a bit much when a semicolon will do :)
