### ISSUE TITLE
keyword argument for config()

### ISSUE THREAD

**Issue by ErwanPiR** [tecosaur/DotEnv.jl#2]
Hi,

I have a problem with the path for the DotEnv.config() function.
When I try to call config with path="user_path" it says that config does not accept keyword arguments : 

`DotEnv.config(path="C:\\users\\...")`

> function config does not accept keyword arguments

Do you have an idea of what the problem could be ?

Thanks.

**Comment by vmari** [comment]
Thank you for your report. I will be fixing this right now.
v0.2.1 fixes this.
Regards

**Comment by ErwanPiR** [comment]
Thank you for the update. However it seems now that DotEnv.config() (with and without path) doesn't work anymore...

`show(DotEnv.config())`
`> nothing` 
`show(DotEnv.config(path="user_path"))`
`> nothing` 

Thanks.

**Comment by ErwanPiR** [comment]
My bad. Just the version of config with a custom path doesn't work !

**Comment by ErwanPiR** [comment]
Ok, I get it. The way that config() works when there is a path specified is different than when no custom path : 
1. `DotEnv.config()` : all the .env in the current directory (I guess)
2. `DotEnv.config(path = "user_path")` : the path is not the directory but the .env file so It adds only the specified file.

Everything works fine. Just a thought, it would be nice to be able to specified the folder that contains .env files for custom path either than just the .env path so to add multiple .env files.

Thanks
