### ISSUE TITLE
NAME="VALUE" is parsed to VALUE"

### ISSUE THREAD

**Issue by Helveg** [tecosaur/DotEnv.jl#3]
Most .env parsers allow you to place quotes around the value of your variables:
```
MY_PATH="~/hello world/whitespace.txt"
```

And it will parse it to the string `~/hello world/whitespace.txt`. Currently DotEnv.jl parses this incorrectly to `~/hello world/whitespace.txt"`

**Comment by vmari** [comment]
Hi! I will add this case to the tests and fix it today. I thought this case was covered. 
Thank you for the report.

**Comment by Helveg** [comment]
I'm using DotEnv v0.2.1, thats what the package manager installed today.

Op vr 5 apr. 2019 17:23 schreef Valentín Mari <notifications@github.com>:

**Comment by Teo-ShaoWei** [comment]
@vmari I've tried it on my local machine and this issue seems to be fixed. So feel free to verify and close the issue.
